# Generated by Django 4.2.1 on 2023-05-23 15:08

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Categories',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('type', models.CharField(choices=[('NE', 'Танки'), ('AR', 'Хиллы'), ('DD', 'ДД'), ('ME', 'Торговцы'), ('GU', 'Гилдмастеры'), ('QU', 'Квестгиверы'), ('BL', 'Кузнецы'), ('LE', 'Кожевники'), ('PO', 'Зельевары'), ('SP', 'Мастера заклинаний')], default='NE', max_length=2)),
                ('title_post', models.CharField(blank=True, max_length=255)),
            ],
        ),
        migrations.CreateModel(
            name='Posts',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=255, verbose_name='Заголовок:')),
                ('text', models.TextField(verbose_name='Содержание:')),
                ('files', models.FileField(upload_to='')),
            ],
        ),
        migrations.CreateModel(
            name='Users',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
                ('post_users', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.posts')),
            ],
        ),
        migrations.AddField(
            model_name='posts',
            name='author',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.users'),
        ),
        migrations.AddField(
            model_name='posts',
            name='category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='board.categories', verbose_name='Категория:'),
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('text_comment', models.TextField(verbose_name='Содержание')),
                ('time_in_comment', models.DateTimeField(auto_now_add=True)),
                ('status', models.BooleanField(default=False, verbose_name='рассматриваемый комментарий')),
                ('link_1', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comment_posts', to='board.posts')),
                ('link_2', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
